### PR TITLE
bugfix, articles and transactions

### PR DESCRIPTION
**Pull request by lsh-0**
bugfix, single bad article was rolling back otherwise successful transaction of 25.

this risk is in the regeneration of other data types as well, but the code is getting quite repetitive and may see a refactor soon.

### CODE REVIEW

**Comment by lsh-0** [comment]
if you guys could merge this once approved and do a regen I'd be grateful.

to do a regenerate, just run `./manage.sh regen` and you should be right: https://github.com/elifesciences/observer/blob/develop/src/observer/management/commands/regen.py

**Comment by seanwiseman** [comment]
@giorgiosironi I can go ahead and run the regen when you are happy to merge.

**Comment by lsh-0** [comment]
> I'd need more detail on what and how big a "logical group" of articles is 

the logical group in this case are all versions of an article. they need to be ingested altogether or not at all. if an article has three versions, then all operations on that article happen within a transaction. that transaction then exists within a larger transaction that commits articles 25 at a time. partly to stop them accumulating in memory and partly to prevent any one object rolling back a very large transaction.

**Comment by giorgiosironi** [comment]
>  if an article has three versions, then all operations on that article happen within a transaction

That seems like a bounded inner transaction, cannot grow too much even with articles that have many versions.

> that transaction then exists within a larger transaction that commits articles 25 at a time

If the inner transaction already covers all the versions, why an outer transaction is needed? Are there table/rows that are not covered by it?

**Comment by lsh-0** [comment]
speed, actually. running all this within a chunked transaction speeds things up considerably. 25 could actually be doubled to be honest, it's a leftover from the import was less stable and batches of 25 meant fewer articles would have to be re-imported if it failed.

**Pull request merged**
