### PR TITLE
Adding build files

### PR DESCRIPTION
**Pull request by giorgiosironi**
For some reason this `Jenkinsfile` is not being picked up.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
There's been a security update that requires the Jenkinsfile to be in the target branch rather than in the forked one.

**Comment by giorgiosironi** [comment]
https://ci--alfred.elifesciences.org/job/test-observer/ builds directly this branch.

**Comment by giorgiosironi** [comment]
The first problem is that `postgres_database.present` is failing, it seems because the password of the root user for the local Postgresql is being refused.

**Comment by lsh-0** [comment]
thanks @giorgiosironi - I'm taking a look at the formula today and giving it a scrub.

**Pull request merged**
