### PR TITLE
Adding smoke tests

### PR DESCRIPTION
**Pull request by giorgiosironi**
It should be safe to run these on all environments, they should never
fail (my assumption)

### CODE REVIEW

**Comment by lsh-0** [comment]
yeah, the reports should always be there regardless of environment. they may be empty in some environments

**Comment by giorgiosironi** [comment]
They give 404 rather than a (200) empty report, see https://ci--alfred.elifesciences.org/job/pull-requests-projects/job/observer/job/PR-14/2/console is that expected?

**Comment by lsh-0** [comment]
might be a problem with trailing slashes. in django world, urls tend to have trailing slashes. I tried to fix that a while ago but I think it just causes 404 now rather than append a slash. I have a PR open that adds format hints. I'll deal with them properly there. for now, just add a slash

**Comment by lsh-0** [comment]
https://observer.elifesciences.org/report/latest-articles/

**Comment by giorgiosironi** [comment]
Now they all works, getting them in the build and verifying they are green everywhere.

**Pull request merged**
